[package]
name = "sdomain_test_plotters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3"
sdomain_test = { git = "https://github.com/Daleth7/sdomain_test" }